//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public long Idequipo { get; set; }
        public string descripcion { get; set; }
        public string familia { get; set; }
        public string modelo { get; set; }
        public Nullable<long> mantenimiento_programado { get; set; }
        public string estadoequipo { get; set; }
        public string condicion { get; set; }
    }
}
