//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public long Idproyecto { get; set; }
        public string Proyecto1 { get; set; }
        public Nullable<System.DateTime> Fechainicio { get; set; }
        public string Descripción { get; set; }

       
    }
}
